In [4]:
import numpy as np
v = np.array([[1],[2], [3]])
v

array([[1],
       [2],
       [3]])

In [11]:
m= np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
m.shape

(3, 3)

In [7]:
north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west = np.array([-1,0])

np.dot(north, south)

-1

$$ A \cdot A^T = I $$

In [14]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

output = np.cross(A, B)
print(output)

[20 -4 -3]


In [25]:
def countdown(n):
    print(n)
    #count backwards from n until we get to 0
    if n>0:
        #stuff
        countdown(n-1)
    else:
        return #stopping condition - terminates the recursion


In [26]:
countdown(3)

3
2
1
0


In [28]:
def countdown(n):

    #count backwards from n until we get to 0
    if n>0:
        #stuff
        countdown(n-1)
        print(n)
    else:
        return #stopping condition - terminates the recursion

In [29]:
countdown(3)

1
2
3


1. Write a function that calculates the dot product manually AND a function that
calculates the cross product manually. Both should accept two vectors and perform
that calculation. Be sure to use try except and error handling for basic issues that
might occur.

In [32]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

output = np.dot(A, B)
print(output)

101


In [39]:
def dot_product(a_vector,b_vector):
 
    return sum([a*b for a,b in zip(a_vector,b_vector)])

X = [1,2,3,4,5,]
Y = [6,7,8,9,10]
print(dot_product(X,Y)) 
a=[1,2,3]
b=[4,5,6]
print(dot_product(a,b)) #prints 32= 1*4 + 2*5 + 3*6 = 
m = [1, 2, 3]
n = [7, 8, 9]
print(dot_product(m,n)) #prints 50 

130
32
50


In [42]:
m = [1, 2, 3]
n = [7, 8, 9]
print(dot_product(m,n))

50


In [43]:
np.dot(m,n)


50

In [71]:
def dot_product (a,b):
    y = 0
    for x in range(a.shape[0]):
        try:
            y += a[x]* b[x]
        except Exception as e:
            print(e)
    else: 
        print(y)


In [72]:
v1= np.array([1, 0, 2, 7])
v2 = np.array([3, 8, 5, 3])

dot_product(v1, v2)

34


In [73]:
np.dot(v1, v2)

34

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])
z= 

In [130]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
#u = np.array([[0, -2, 0]])
#+4*u
x = 3*v-2*w
print(x)

[[-8  7  4]]


In [131]:
print(np.cross(v, w))

[[  1   8 -12]]


In [144]:
def cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
         a[2]*b[0] - a[0]*b[2],
         a[0]*b[1] - a[1]*b[0]]

    return c
cross([1, 2, -1], [2, 0, -1, 3])

[-2, -1, -4]

In [142]:
x = np.array([1, 2, -1])
y = np.array([2, 0, -1])

print(np.cross(x, y))

[-2 -1 -4]


In [163]:
def cross(a, b):
    #assert len(a) == len(b) == 3,
    return [a[-7]*b[4] - a[1]*b[2],
            a[1]*b[5]  - a[1]*b[4],
            a[1]*b[2]  - a[-7]*b[5]]

cross([1, -7, 1], [5, 2, 4, 3])

IndexError: list index out of range

In [158]:
def cross_product(a, b):
    assert len(a) == len(b) == 3, 'Vectors a, b must be three-dimensional'
    return [a[1]*b[2] - a[2]*b[1],
            a[2]*b[0] - a[0]*b[2],
            a[0]*b[1] - a[1]*b[0]]

    cross_product([1, 2, -1], [2, 0, -1, 3])
print(cross_product)

<function cross_product at 0x000001F0CEEE0940>


In [122]:
x = np.array([1, -7, 1])
y = np.array([5, 2, 4])
print(np.cross(x,y))

[-30   1  37]


In [113]:
z = x*y
print(z)

[  5 -14   4]


In [111]:
print(np.cross(x, y))

[-30   1  37]


In [46]:
data = np.array([1, 0, 3, 1])
shape = (data.size, data.max()+1)
one_hot = np.zeros(shape)
rows = np.arange(data.size)
print(rows)

[0 1 2 3]


In [47]:
one_hot[rows, data] = 1
print(one_hot)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [48]:
a = np.array([1, 0, 3])
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1
b

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

calculate a one hot encoding for the Belize_Airbnb_listings.csv
neighborhood_group column.

In [184]:
import pandas as pd
import numpy as np
belize_listings = "A:/launch_code_STL/Final_Homework/week-4/belize_airbnb_listings.csv"
belize_df = pd.read_csv(belize_listings)

In [185]:
belize_df.head(1)

id                                        name  host_id host_name  \
0  36666  Mo's Cozy Casa w/ veranda & access to dock   157752   Monique   

  neighbourhood_group   neighbourhood  latitude  longitude        room_type  \
0              Belize  Belize Islands  17.74786  -88.02398  Entire home/apt   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0    141               3                250   2/23/2021                2.0   

   calculated_host_listings_count  availability_365  
0                               5               225

In [197]:
x=belize_df['neighbourhood_group'].value_counts()
x

Belize         1574
Stann Creek     577
Cayo            505
Corozal          65
Toledo           47
Orange Walk      28
Name: neighbourhood_group, dtype: int64

In [189]:
replace_grp = {'neighbourhood_group':{'Belize' : 1, 'Stann Creek' : 2, 'Cayo' : 3,
                                     'Corozal' : 4, 'Toledo' : 5, 'Orange Walk' : 6}}

In [190]:
labels = belize_df['neighbourhood_group'].astype('category').cat.categories.tolist()
replace_grp_comp = {'neighbourhood_group': {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}
print(replace_grp_comp)

{'neighbourhood_group': {'Belize': 1, 'Cayo': 2, 'Corozal': 3, 'Orange Walk': 4, 'Stann Creek': 5, 'Toledo': 6}}


In [191]:
belize_df_replace = belize_df.copy()

In [192]:
belize_df_replace.replace(replace_grp_comp, inplace=True)

print(belize_df_replace.head())

       id                                               name  host_id  \
0   36666         Mo's Cozy Casa w/ veranda & access to dock   157752   
1   36690  Mo's Cozy Cabana w/ comfy veranda & access to ...   157752   
2  108932  Purple House eco solar  w/ ocean & wildlife views   563377   
3  110483                            Michelo's fuchsia suite   567809   
4  120115               Seaside Villas Second Floor Unit  #4   604999   

  host_name  neighbourhood_group         neighbourhood  latitude  longitude  \
0   Monique                    1        Belize Islands  17.74786  -88.02398   
1   Monique                    1        Belize Islands  17.74832  -88.02474   
2   Michael                    1        Belize Islands  17.73221  -88.03824   
3    Michel                    5  Stann Creek Mainland  16.52114  -88.36926   
4     Bobbi                    1        Belize Islands  17.74166  -88.02395   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0  Entire 

In [233]:
a = ohe
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1
b

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [217]:
ohe = belize_df_replace['neighbourhood_group']
ohe.head()

0    1
1    1
2    1
3    5
4    1
Name: neighbourhood_group, dtype: int64

In [226]:
data = belize_df['neighbourhood_group']
print(data)
# define universe of possible input values
alphabet = 'abcdefghijklmnopqrst'
# define a mapping of chars to integers
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)
# one hot encode
onehot_encoded = list()
for value in integer_encoded:
    letter = [0 for _ in range(len(alphabet))]
    letter[value] = 1
    onehot_encoded.append(letter)
print(onehot_encoded)


0            Belize
1            Belize
2            Belize
3       Stann Creek
4            Belize
           ...     
2791         Belize
2792        Corozal
2793         Belize
2794         Belize
2795           Cayo
Name: neighbourhood_group, Length: 2796, dtype: object


KeyError: 'Belize'

In [224]:
data = belize_df['neighbourhood_group']
print(data)

0            Belize
1            Belize
2            Belize
3       Stann Creek
4            Belize
           ...     
2791         Belize
2792        Corozal
2793         Belize
2794         Belize
2795           Cayo
Name: neighbourhood_group, Length: 2796, dtype: object


In [ ]:
onehot_encoded = list()
for value in integer_encoded:
	letter = [0 for _ in range(len(alphabet))]
	letter[value] = 1
	onehot_encoded.append(letter)
print(onehot_encoded)

In [2]:
M1 = [[8, 14, -6], [12,7,4], [-11,3,21]]
print(M1)

[[8, 14, -6], [12, 7, 4], [-11, 3, 21]]


In [13]:
M1 = [[8, 14, -6], 
      [12,7,4], 
      [-11,3,21]]

matrix_length = len(M1)

for i in range(matrix_length):
    #print(M1[i][-1]) #To read the last element from each row.
    print(M1[i]) #To print the rows in the Matrix

[8, 14, -6]
[12, 7, 4]
[-11, 3, 21]


In [17]:
import numpy as np
arr = np.array([2,4,6,8,10,12,14,16])
print(arr[-3:])

[12 14 16]


In [19]:
m1 = [[8, 14, -6], [12,7,4], [-11,3,21]]
m3 = [[2, 13, -3], [18,9,5], [10,4,27]]

m2 = np.linalg.solve(m1, m3)
m2

array([[ 1.16675575,  0.17664351, -0.18198824],
       [-0.0545163 ,  0.89417424,  0.37680385],
       [ 1.09513629,  0.15526456,  1.13655799]])

In [20]:
import numpy as np
v1 = [6, 0, 3, 1, 4, 2];
v2 = [0, -1, 2, 7, 0, 5];
v3 = [12, 3, 0, -19, 8, -11];

A = np.row_stack([v1, v2, v3])

# matlab definition
eps = np.finfo(np.linalg.norm(A).dtype).eps
TOLERANCE = max(eps * np.array(A.shape))

U, s, V = np.linalg.svd(A)
print(s)
print(np.sum(s > TOLERANCE))

TOLERANCE = 1e-14
print(np.sum(s > TOLERANCE))

[2.75209239e+01 9.30584482e+00 1.42425400e-15]
3
2


In [1]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


In [4]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)


[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0
