In [4]:
import numpy as np
v = np.array([[1],[2], [3]])
v

array([[1],
       [2],
       [3]])

In [11]:
m= np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
m.shape

(3, 3)

In [7]:
north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west = np.array([-1,0])

np.dot(north, south)

-1

$$ A \cdot A^T = I $$

In [14]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

output = np.cross(A, B)
print(output)

[20 -4 -3]


In [25]:
def countdown(n):
    print(n)
    #count backwards from n until we get to 0
    if n>0:
        #stuff
        countdown(n-1)
    else:
        return #stopping condition - terminates the recursion


In [26]:
countdown(3)

3
2
1
0


In [28]:
def countdown(n):

    #count backwards from n until we get to 0
    if n>0:
        #stuff
        countdown(n-1)
        print(n)
    else:
        return #stopping condition - terminates the recursion

In [29]:
countdown(3)

1
2
3


1. Write a function that calculates the dot product manually AND a function that
calculates the cross product manually. Both should accept two vectors and perform
that calculation. Be sure to use try except and error handling for basic issues that
might occur.

In [32]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

output = np.dot(A, B)
print(output)

101


In [39]:
def dot_product(a_vector,b_vector):
 
    return sum([a*b for a,b in zip(a_vector,b_vector)])

X = [1,2,3,4,5,]
Y = [6,7,8,9,10]
print(dot_product(X,Y)) 
a=[1,2,3]
b=[4,5,6]
print(dot_product(a,b)) #prints 32= 1*4 + 2*5 + 3*6 = 
m = [1, 2, 3]
n = [7, 8, 9]
print(dot_product(m,n)) #prints 50 

130
32
50


In [42]:
m = [1, 2, 3]
n = [7, 8, 9]
print(dot_product(m,n))

50


In [43]:
np.dot(m,n)


50

In [45]:
def dot_product (a,b):
    y = 0
    for x in range(v.shape[0]):
        try:
            y += a[x]* b[x]
        except Exception as e:
            print(e)
    else: 
        print(y)


In [ ]:
v= np.array([])